language: node_js
node_js: stable

# S: Build Lifecycle
before_install:
  - npm install -g hexo
  - npm install -g hexo-cli
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo g

before_script:
- git config --global user.name 'ioliu'
- git config --global user.email '1256141550@qq.com'
- sed -i'' "s~git@github.com:ioliu/ioliu.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/ioliu/ioliu.github.io.git~" _config.yml
after_success:
- hexo deploy

branches:
  only:
    - blogs
env:
 global:
   - GH_REF: github.com/ioliu/ioliu.github.io.git
